"""Pydantic v2 output contract for cg_recognition's proposed-structure object
(Phase 35: RCGN-01).

Division of labour, in one sentence: **Pydantic guarantees the shape,
`cg_recognition.validate_proposed_structure()` guarantees the safety.**

The RELATIONAL rules -- a member id must exist in the submitted context, must
not already belong to a tagged (ground-truth) entity, must not be claimed twice
-- are not expressible in JSON Schema because they are relations between the
proposal and the submitted `cg_context`. They stay in
`validate_proposed_structure()` and this module never duplicates them.

Three checks, three different jobs:

1. Provider-native constrained decoding (via `to_strict_json_schema`) shapes the
   output at generation time -- best effort, and only where the provider
   supports it.
2. `ProposedStructure.model_validate()` re-checks shape AND value ranges after
   parsing -- notably `confidence` in [0.0, 1.0], whose bound is deliberately
   STRIPPED from the wire schema (see `to_strict_json_schema`).
3. `validate_proposed_structure()` checks the relational safety contract
   (RCGN-04) -- tagged_overlap, duplicate_member, unknown_member_id, DoS bounds.

Field `description` strings are prompt surface, not documentation: under
provider-native structured outputs the model reads them. `suggestedName` and
`rationale` therefore carry the grammar-anti-filter framing (UAT F3 root cause)
into the one place a strict-mode model definitely sees.
"""

from __future__ import annotations

import copy
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# Both spellings are legal, because ProposalDto.ToEntityTagKind()
# (DG/src/DG.Grasshopper/Canvas/PreviewRegistry.cs:110-123) accepts the short
# EntityTagKind names AND the long catalog entity-class kinds the prompt
# teaches -- and THROWS on anything else. Narrowing to one spelling here would
# break one side or the other. Mirrors cg_recognition.ALLOWED_PROPOSAL_KINDS;
# declared literally rather than imported to avoid a circular import, since
# cg_recognition imports this module. A test asserts the two stay equal.
# "Algorithm" is deliberately absent -- proposals are group-level entities only.
ProposalKind = Literal[
    "Proc", "Procedure",
    "Pat", "Pattern",
    "Var", "VariableParam",
    "Const", "ConstantParam",
    "Emg", "EmergentParam",
    "IntF", "Interface",
]


class StructureProposal(BaseModel):
    """One proposed Computgraph entity over a set of untagged canvas nodes."""

    model_config = ConfigDict(extra="forbid")  # -> additionalProperties: false

    kind: ProposalKind = Field(
        description=(
            "The Computgraph entity class this group of components implements."
        )
    )
    suggestedName: str = Field(
        description=(
            "The name to CREATE for this entity, written in the DG annotation "
            "convention, e.g. '11_IntF_ParSplitAt'. This is generated by you; it "
            "is NOT expected to match the node's existing nickname."
        )
    )
    procedureIndex: int = Field(
        description="Owning procedure index, e.g. 11 = algorithm 1, procedure 1."
    )
    memberIds: list[str] = Field(
        description="instanceId values copied verbatim from the submitted context."
    )
    confidence: Annotated[float, Field(ge=0.0, le=1.0)] = Field(
        description=(
            "0.0-1.0. Renders on canvas as a percentage and is the architect's "
            "triage signal. A confidently wrong proposal costs more than an "
            "honest 'unrecognized' entry -- prefer abstaining."
        )
    )
    rationale: str = Field(
        description=(
            "<= 30 words. Cite GRAPH EVIDENCE (degree, wiring, group membership, "
            "adjacent tagged procedure). Do NOT cite the naming grammar."
        )
    )


class UnrecognizedBlock(BaseModel):
    """Nodes the model could not ground in graph evidence.

    Abstaining is a good answer: an honest unrecognized entry costs the
    architect less than a confidently wrong proposal.
    """

    model_config = ConfigDict(extra="forbid")

    memberIds: list[str] = Field(
        description="instanceId values copied verbatim from the submitted context."
    )
    reason: str = Field(
        description=(
            "Name the MISSING evidence, e.g. 'isolated: no wires in or out -- "
            "cannot distinguish a constant from an abandoned experiment'."
        )
    )


class ProposedStructure(BaseModel):
    """The complete recognition output: proposals plus honest abstentions."""

    model_config = ConfigDict(extra="forbid")

    proposals: list[StructureProposal] = Field(
        description="One entry per proposed entity. Do not pad this list."
    )
    unrecognized: list[UnrecognizedBlock] = Field(
        default_factory=list,
        description=(
            "One entry per block you could not ground. Every scoped candidate id "
            "must appear in exactly one of proposals[].memberIds or "
            "unrecognized[].memberIds -- never silently dropped."
        ),
    )


# ── Generated-candidate output contract (Phase 38: GHIN-03) ──
#
# D-17, stated plainly: this schema conveys SHAPE ONLY. `to_strict_json_schema`
# strips `minimum`/`maximum` below (L205-221 at the time this note was
# written), and the real bounds here are per-parameter and dynamic anyway --
# no wire schema could express them. Domain enforcement is
# `cg_input_sampler.validate_candidate`, not this contract. Anyone tempted to
# add a numeric-bound Field constraint to `GeneratedParameterValue` should
# read this note first: it would be silently stripped at the wire boundary
# and would give a false impression that the model's raw output is
# bounds-checked here.


class GeneratedParameterValue(BaseModel):
    """One parameter value inside a generated candidate."""

    model_config = ConfigDict(extra="forbid")

    parameterId: str = Field(
        description="The bound parameter's reinstateParameterId, copied verbatim -- never invented."
    )
    type: str = Field(
        description=(
            "One of 'Number' | 'Integer' | 'Boolean'. Not a Literal -- validity is checked by "
            "cg_input_sampler.validate_candidate against the actual bound parameter set, not "
            "the wire schema (mirrors dg_context.py's ContextAssembleRequest.type convention)."
        )
    )
    numberValue: "float | None" = Field(None, description="Set only when type == 'Number'.")
    integerValue: "int | None" = Field(None, description="Set only when type == 'Integer'.")
    booleanValue: "bool | None" = Field(None, description="Set only when type == 'Boolean'.")


class GeneratedCandidate(BaseModel):
    """One proposed parameter assignment for a rule's bound parameters."""

    model_config = ConfigDict(extra="forbid")

    strategy: str = Field(
        description="One of 'conservative' | 'balanced' | 'exploratory' | 'near-limit'."
    )
    rationale: str = Field(description="A one-sentence rationale for this candidate's values.")
    parameters: list[GeneratedParameterValue] = Field(
        description="One entry per bound parameter this candidate assigns a value to."
    )


class GeneratedCandidateSet(BaseModel):
    """The complete generation output: exactly one candidate per requested strategy."""

    model_config = ConfigDict(extra="forbid")

    candidates: list[GeneratedCandidate] = Field(
        description="One entry per candidate. Do not pad this list."
    )


# ── Provider-acceptable JSON Schema emission ──

# Keywords neither OpenAI strict nor Anthropic accept in a structured-output
# schema. Pydantic emits `minimum`/`maximum` for confidence's ge/le bound; the
# bound is NOT lost by stripping it here, because model_validate() still
# enforces it after parsing.
_UNSUPPORTED_KEYWORDS = (
    "minimum",
    "maximum",
    "exclusiveMinimum",
    "exclusiveMaximum",
    "minLength",
    "maxLength",
    "pattern",
    "minItems",
    "maxItems",
)


def _resolve_refs(node: Any, defs: dict[str, Any], _depth: int = 0) -> Any:
    """Inline every $ref against `defs`, recursively.

    Anthropic rejects external $ref and OpenAI's handling of nested $defs is
    version-sensitive, so the safest move for a schema this small is to
    flatten it entirely. Bounded depth guards a self-referential model (none
    exist here today, but a future nested entity could introduce one).
    """
    if _depth > 20:
        return node

    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str) and ref.startswith("#/$defs/"):
            target = defs.get(ref.rsplit("/", 1)[-1], {})
            merged = _resolve_refs(copy.deepcopy(target), defs, _depth + 1)
            # Preserve any sibling keys declared alongside the $ref.
            siblings = {k: v for k, v in node.items() if k != "$ref"}
            if isinstance(merged, dict):
                merged.update(_resolve_refs(siblings, defs, _depth + 1))
                return merged
            return merged
        return {k: _resolve_refs(v, defs, _depth + 1) for k, v in node.items()}

    if isinstance(node, list):
        return [_resolve_refs(item, defs, _depth + 1) for item in node]

    return node


def _tighten(node: Any) -> Any:
    """Apply the strict-subset rules to every object node, recursively.

    - `additionalProperties: false` on every object (asserted, not assumed --
      Pydantic emits it only under extra="forbid").
    - every key of `properties` present in `required`. OpenAI strict expresses
      optionality as a null union, NEVER by omission, so `unrecognized` must be
      required here even though it defaults to [] in Python.
    - unsupported keywords stripped.
    """
    if isinstance(node, dict):
        out = {k: _tighten(v) for k, v in node.items() if k not in _UNSUPPORTED_KEYWORDS}
        if out.get("type") == "object" or "properties" in out:
            out["additionalProperties"] = False
            properties = out.get("properties")
            if isinstance(properties, dict):
                out["required"] = list(properties.keys())
        return out

    if isinstance(node, list):
        return [_tighten(item) for item in node]

    return node


def to_strict_json_schema(model: type[BaseModel]) -> dict:
    """Pydantic v2 JSON Schema -> the OpenAI-strict / Anthropic-compatible subset.

    The emitted schema is **deliberately weaker than the Pydantic model**: the
    numeric bound on `confidence` is stripped because neither provider supports
    `minimum`/`maximum` in a structured-output schema. That is intended, not a
    leak -- constrained decoding gives you the structure, `model_validate()`
    re-checks the value ranges after parsing, and
    `validate_proposed_structure()` then checks the relational safety rules.

    Never mutates Pydantic's cached schema: the returned dict is a deep copy.
    """
    schema = copy.deepcopy(model.model_json_schema())
    defs = schema.pop("$defs", {})
    resolved = _resolve_refs(schema, defs)
    return _tighten(resolved)
