"""Tests for design_state_projection.py (Phase 1202 Plan 02, ALGN12-08/ALGN12-09).

Cross-language parity twin: DG/tests/DG.Tests/DesignStateCanonicalProjectionTests.cs's
ComputeHash_ShouldMatchSharedCrossLanguageVector Fact. Both suites assert the SAME hard-coded
64-char uppercase hex constant for the equivalent input -- a divergence in either language fails
that language's test before any DE-01 cross-leg comparison could report it (the CR-01/WR-01
precedent, 1202-CONTEXT.md T-1202-04).
"""
import copy
import json
import os
import sys
from decimal import Decimal
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest

from design_state_projection import build_projection, compute_state_hash

# Twin of DG/tests/DG.Tests/DesignStateCanonicalProjectionTests.cs's SharedVectorHash constant,
# generated by actually running DesignStateCanonicalProjection.ComputeHash against the equivalent
# fixed DesignState (see 1202-02-SUMMARY.md) -- not guessed independently on this side.
SHARED_VECTOR_HASH = "4A4CAB67B35F6F9B3A0E42BA56C5A366673675CBC871DFA302058977CC34E09E"


def _repo_root() -> Path:
    mnt = Path("/mnt/repo")
    if mnt.exists():
        return mnt
    return Path(__file__).resolve().parent.parent.parent


def _shared_vector_payload() -> dict:
    """The v2 wire-payload equivalent of DesignStateCanonicalProjectionTests.cs's
    BuildFixedDesignStateWithParameter() fixture -- same stateIds, same values, same
    capturedAtUtc strings, so build_projection() on this dict must hash identically to the C#
    ComputeHash() call on the equivalent in-memory DesignState.
    """
    return {
        "version": "2",
        "stateId": "DS_1202_VECTOR_01",
        "label": "1202 shared vector",
        "capturedAtUtc": "2026-09-21T12:00:00.0000000Z",
        "objStates": [
            {
                "stateId": "OS_1202_A",
                "objectRef": "OBJ_A",
                "label": "Object A",
                "classIri": "ex:Building",
                "dgId": "dg:AAAAAAAAAAAAAAAA",
                "capturedAtUtc": "2026-09-21T12:00:00.0000000Z",
            },
            {
                "stateId": "OS_1202_B",
                "objectRef": "OBJ_B",
                "label": "Object B",
                "classIri": "ex:Site",
                "dgId": None,
                "capturedAtUtc": "2026-09-21T12:00:01.0000000Z",
            },
        ],
        "paramStates": [
            {
                "stateId": "DS_1202_PARAMS_01",
                "capturedAtUtc": "2026-09-21T12:00:02.0000000Z",
                "parameters": [
                    {
                        "parameterId": "HeightSlider",
                        "displayName": "Height Slider",
                        "type": "number",
                        "value": 42.0,
                    }
                ],
            }
        ],
        "propStates": [
            {
                "stateId": "PS_1202_HEIGHT_01",
                "ruleIri": "R_GOLD_HEIGHT_MAX_75_V",
                "dataPropertyIri": "ex:hasHeight",
                "objectRef": "OBJ_A",
                "propValue": {
                    "parameterId": "hasHeight",
                    "displayName": "Has Height",
                    "type": "number",
                    "value": 42.0,
                },
            }
        ],
    }


def test_compute_state_hash_matches_shared_cross_language_vector():
    payload = _shared_vector_payload()

    digest = compute_state_hash(payload)

    assert len(digest) == 64
    assert digest == digest.upper()
    assert digest == SHARED_VECTOR_HASH


def test_build_projection_is_order_independent_for_member_list_order():
    payload = _shared_vector_payload()
    reordered = copy.deepcopy(payload)
    reordered["objStates"] = list(reversed(reordered["objStates"]))

    assert compute_state_hash(payload) == compute_state_hash(reordered)


def test_build_projection_excludes_geometry_key_if_present():
    # The v2 wire payload never carries a geometry key to begin with (D-06 is structural on the
    # wire shape itself), but a producer that accidentally includes one must not have it affect
    # the hash -- build_projection() only ever reads the documented keys off each objState entry.
    payload = _shared_vector_payload()
    with_stray_geometry = copy.deepcopy(payload)
    with_stray_geometry["objStates"][0]["geometry"] = {"speckleObjectId": "abc123"}

    assert compute_state_hash(payload) == compute_state_hash(with_stray_geometry)


def test_build_projection_malformed_payload_missing_version_raises():
    payload = _shared_vector_payload()
    del payload["version"]

    with pytest.raises(ValueError):
        build_projection(payload)


def test_build_projection_malformed_payload_missing_member_state_id_raises():
    payload = _shared_vector_payload()
    del payload["objStates"][0]["stateId"]

    with pytest.raises(ValueError):
        build_projection(payload)


def test_compute_state_hash_raises_on_nan_number_value():
    payload = _shared_vector_payload()
    payload["paramStates"][0]["parameters"].append(
        {
            "parameterId": "BadParam",
            "displayName": "Bad Param",
            "type": "number",
            "value": float("nan"),
        }
    )

    with pytest.raises(ValueError):
        compute_state_hash(payload)


def test_compute_state_hash_raises_on_infinite_number_value():
    payload = _shared_vector_payload()
    payload["paramStates"][0]["parameters"].append(
        {
            "parameterId": "InfiniteParam",
            "displayName": "Infinite Param",
            "type": "number",
            "value": float("inf"),
        }
    )

    with pytest.raises(ValueError):
        compute_state_hash(payload)


def test_build_projection_members_manifest_lists_every_member_sorted():
    payload = _shared_vector_payload()

    projection = build_projection(payload)
    members = projection["members"]

    assert len(members) == 4
    kinds = [m["kind"] for m in members]
    assert kinds == sorted(kinds)
    assert {"kind": "objState", "stateId": "OS_1202_A"} in members
    assert {"kind": "objState", "stateId": "OS_1202_B"} in members
    assert {"kind": "paramState", "stateId": "DS_1202_PARAMS_01"} in members
    assert {"kind": "propState", "stateId": "PS_1202_HEIGHT_01"} in members


def test_build_projection_converts_number_parameter_to_decimal():
    payload = _shared_vector_payload()

    projection = build_projection(payload)
    parameter_value = projection["paramStates"][0]["parameters"][0]["value"]

    assert isinstance(parameter_value, Decimal)
    assert parameter_value == Decimal("42.0") or parameter_value == Decimal("42")


def test_serializer_never_calls_hashlib_directly():
    """Grep-verifiable acceptance criterion: no second hasher.

    Mirrors the plan's own acceptance check
    (``grep -v '^\\s*#' data-service/design_state_projection.py | grep -cE 'hashlib|sha256'``
    returns 0) rather than a line-by-line scan here, so prose in the module docstring that
    merely *mentions* hashlib/sha256 (to explain why they must not appear in code) cannot
    trip this test the way a naive per-line substring scan would.
    """
    module_path = Path(__file__).resolve().parent.parent / "design_state_projection.py"
    code_lines = [
        line for line in module_path.read_text(encoding="utf-8").splitlines()
        if not line.strip().startswith("#")
    ]
    code_only = "\n".join(code_lines)
    assert "import hashlib" not in code_only
    assert "hashlib." not in code_only
    assert "sha256(" not in code_only
    assert "hash_canonical" in code_only


def test_fixture_expected_canonical_state_hash_is_populated():
    fixture_path = _repo_root() / "fixtures" / "golden" / "replay" / "mixed-verdicts.json"
    with open(fixture_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    digest = data["expectedCanonicalStateHash"]
    assert isinstance(digest, str)
    assert len(digest) == 64
    assert digest == digest.upper()
    assert data["canonicalizationVersion"] == 1


def test_fixture_canonical_state_hash_is_independently_reproducible():
    """Recompute the fixture's own canonicalStateHash from its embedded statePayloadJson rather
    than trusting the recorded literal -- the CR-01/WR-01 double-check discipline.
    """
    fixture_path = _repo_root() / "fixtures" / "golden" / "replay" / "mixed-verdicts.json"
    with open(fixture_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    payload = json.loads(data["statePayloadJson"], parse_float=Decimal)
    recomputed = compute_state_hash(payload)

    assert recomputed == data["expectedCanonicalStateHash"]
