using DG.Core.Models;
using DG.Core.Serialization;

namespace DG.Tests;

public sealed class DesignStateCanonicalProjectionTests
{
    // Generated by actually running ComputeHash_ShouldMatchSharedCrossLanguageVector once and
    // pasting the observed value (see 1202-02-SUMMARY.md) -- not guessed. Task 2's Python test
    // (data-service/tests/test_design_state_projection.py) asserts the identical literal for
    // cross-language parity.
    private const string SharedVectorHash = "4A4CAB67B35F6F9B3A0E42BA56C5A366673675CBC871DFA302058977CC34E09E";

    private static DesignState BuildFixedDesignState()
    {
        return new DesignState
        {
            StateId = "DS_1202_VECTOR_01",
            Label = "1202 shared vector",
            CapturedAtUtc = new DateTimeOffset(2026, 9, 21, 12, 0, 0, DateTimeOffset.UtcNow.Offset).ToUniversalTime(),
            ObjStates = new List<ObjState>
            {
                new()
                {
                    StateId = "OS_1202_A",
                    ObjectRef = "OBJ_A",
                    Label = "Object A",
                    ClassIri = "ex:Building",
                    CapturedAtUtc = DateTimeOffset.Parse("2026-09-21T12:00:00.0000000Z").ToUniversalTime(),
                    DgId = "dg:AAAAAAAAAAAAAAAA",
                },
                new()
                {
                    StateId = "OS_1202_B",
                    ObjectRef = "OBJ_B",
                    Label = "Object B",
                    ClassIri = "ex:Site",
                    CapturedAtUtc = DateTimeOffset.Parse("2026-09-21T12:00:01.0000000Z").ToUniversalTime(),
                    DgId = null,
                },
            },
            ParamStates = new List<ParamState>
            {
                new()
                {
                    StateId = "DS_1202_PARAMS_01",
                    CapturedAtUtc = DateTimeOffset.Parse("2026-09-21T12:00:02.0000000Z").ToUniversalTime(),
                },
            },
            PropStates = new List<PropState>
            {
                new()
                {
                    StateId = "PS_1202_HEIGHT_01",
                    RuleIri = "R_GOLD_HEIGHT_MAX_75_V",
                    DataPropertyIri = "ex:hasHeight",
                    ObjectRef = "OBJ_A",
                    PropValue = new DesignStateParameter
                    {
                        ParameterId = "hasHeight",
                        DisplayName = "Has Height",
                        Type = DesignStateParameterType.Number,
                        NumberValue = 42.0,
                    },
                },
            },
        };
    }

    private static DesignState BuildFixedDesignStateWithParameter()
    {
        var state = BuildFixedDesignState();
        state.ParamStates[0].Parameters.Add(new DesignStateParameter
        {
            ParameterId = "HeightSlider",
            DisplayName = "Height Slider",
            Type = DesignStateParameterType.Number,
            NumberValue = 42.0,
        });
        return state;
    }

    [Fact]
    public void ComputeHash_ShouldMatchSharedCrossLanguageVector()
    {
        var state = BuildFixedDesignStateWithParameter();

        var hash = DesignStateCanonicalProjection.ComputeHash(state);

        Assert.Equal(64, hash.Length);
        Assert.Equal(hash, hash.ToUpperInvariant());
        Assert.Equal(SharedVectorHash, hash);
    }

    [Fact]
    public void Build_ShouldBeOrderIndependent_ForMemberListOrder()
    {
        var state = BuildFixedDesignStateWithParameter();
        var reordered = new DesignState
        {
            StateId = state.StateId,
            Label = state.Label,
            CapturedAtUtc = state.CapturedAtUtc,
            ObjStates = state.ObjStates.AsEnumerable().Reverse().ToList(),
            ParamStates = state.ParamStates,
            PropStates = state.PropStates,
        };

        var hash1 = DesignStateCanonicalProjection.ComputeHash(state);
        var hash2 = DesignStateCanonicalProjection.ComputeHash(reordered);

        Assert.Equal(hash1, hash2);
    }

    [Fact]
    public void Build_ShouldExcludeGeometry_SoNullOrNonNullGeometryHashesIdentically()
    {
        var state = BuildFixedDesignStateWithParameter();
        var withGeometry = new DesignState
        {
            StateId = state.StateId,
            Label = state.Label,
            CapturedAtUtc = state.CapturedAtUtc,
            ObjStates = state.ObjStates
                .Select(o => new ObjState
                {
                    StateId = o.StateId,
                    ObjectRef = o.ObjectRef,
                    Label = o.Label,
                    ClassIri = o.ClassIri,
                    CapturedAtUtc = o.CapturedAtUtc,
                    DgId = o.DgId,
                    Geometry = new object(),
                })
                .ToList(),
            ParamStates = state.ParamStates,
            PropStates = state.PropStates,
        };

        var hashWithoutGeometry = DesignStateCanonicalProjection.ComputeHash(state);
        var hashWithGeometry = DesignStateCanonicalProjection.ComputeHash(withGeometry);

        Assert.Equal(hashWithoutGeometry, hashWithGeometry);
    }

    [Fact]
    public void Build_ShouldChangeHash_WhenClassIriChanges()
    {
        var state = BuildFixedDesignStateWithParameter();
        var mutated = new DesignState
        {
            StateId = state.StateId,
            Label = state.Label,
            CapturedAtUtc = state.CapturedAtUtc,
            ObjStates = new List<ObjState>
            {
                new()
                {
                    StateId = state.ObjStates[0].StateId,
                    ObjectRef = state.ObjStates[0].ObjectRef,
                    Label = state.ObjStates[0].Label,
                    ClassIri = "ex:DifferentClass",
                    CapturedAtUtc = state.ObjStates[0].CapturedAtUtc,
                    DgId = state.ObjStates[0].DgId,
                },
                state.ObjStates[1],
            },
            ParamStates = state.ParamStates,
            PropStates = state.PropStates,
        };

        var hash1 = DesignStateCanonicalProjection.ComputeHash(state);
        var hash2 = DesignStateCanonicalProjection.ComputeHash(mutated);

        Assert.NotEqual(hash1, hash2);
    }

    [Fact]
    public void Build_ShouldChangeHash_WhenDesignStateLabelChanges()
    {
        var state = BuildFixedDesignStateWithParameter();
        var relabeled = new DesignState
        {
            StateId = state.StateId,
            Label = "A different label",
            CapturedAtUtc = state.CapturedAtUtc,
            ObjStates = state.ObjStates,
            ParamStates = state.ParamStates,
            PropStates = state.PropStates,
        };

        var hash1 = DesignStateCanonicalProjection.ComputeHash(state);
        var hash2 = DesignStateCanonicalProjection.ComputeHash(relabeled);

        Assert.NotEqual(hash1, hash2);
    }

    [Fact]
    public void Build_ShouldChangeHash_WhenObjStateLabelChanges()
    {
        var state = BuildFixedDesignStateWithParameter();
        var mutated = new DesignState
        {
            StateId = state.StateId,
            Label = state.Label,
            CapturedAtUtc = state.CapturedAtUtc,
            ObjStates = new List<ObjState>
            {
                new()
                {
                    StateId = state.ObjStates[0].StateId,
                    ObjectRef = state.ObjStates[0].ObjectRef,
                    Label = "Renamed Object A",
                    ClassIri = state.ObjStates[0].ClassIri,
                    CapturedAtUtc = state.ObjStates[0].CapturedAtUtc,
                    DgId = state.ObjStates[0].DgId,
                },
                state.ObjStates[1],
            },
            ParamStates = state.ParamStates,
            PropStates = state.PropStates,
        };

        var hash1 = DesignStateCanonicalProjection.ComputeHash(state);
        var hash2 = DesignStateCanonicalProjection.ComputeHash(mutated);

        Assert.NotEqual(hash1, hash2);
    }

    [Fact]
    public void Build_ShouldRepresentAbsentOptionalMembers_AsJsonNull()
    {
        var state = BuildFixedDesignStateWithParameter();

        var projection = DesignStateCanonicalProjection.Build(state);
        var objStates = projection["objStates"]!.AsArray();
        var objB = objStates.Single(o => o!["stateId"]!.GetValue<string>() == "OS_1202_B");

        Assert.Null(objB!["dgId"]);
        Assert.NotNull(projection["objStates"]);
    }

    [Fact]
    public void Build_MembersArray_ShouldListEveryMember_SortedByKindThenStateId()
    {
        var state = BuildFixedDesignStateWithParameter();

        var projection = DesignStateCanonicalProjection.Build(state);
        var members = projection["members"]!.AsArray();

        Assert.Equal(4, members.Count);

        var kinds = members.Select(m => m!["kind"]!.GetValue<string>()).ToList();
        var sortedKinds = kinds.OrderBy(k => k, StringComparer.Ordinal).ToList();
        Assert.Equal(sortedKinds, kinds);

        Assert.Contains(members, m => m!["kind"]!.GetValue<string>() == "objState" && m["stateId"]!.GetValue<string>() == "OS_1202_A");
        Assert.Contains(members, m => m!["kind"]!.GetValue<string>() == "objState" && m["stateId"]!.GetValue<string>() == "OS_1202_B");
        Assert.Contains(members, m => m!["kind"]!.GetValue<string>() == "paramState" && m["stateId"]!.GetValue<string>() == "DS_1202_PARAMS_01");
        Assert.Contains(members, m => m!["kind"]!.GetValue<string>() == "propState" && m["stateId"]!.GetValue<string>() == "PS_1202_HEIGHT_01");
    }

    [Fact]
    public void Build_ShouldConvertDoubleParameterValue_ToDecimal_WithoutThrowing()
    {
        var state = BuildFixedDesignStateWithParameter();

        var projection = DesignStateCanonicalProjection.Build(state);
        var paramStates = projection["paramStates"]!.AsArray();
        var parameters = paramStates[0]!["parameters"]!.AsArray();

        Assert.Equal(42.0m, parameters[0]!["value"]!.GetValue<decimal>());
    }

    [Fact]
    public void ComputeHash_ShouldThrow_WhenNumberParameterValueIsNaN()
    {
        var state = BuildFixedDesignStateWithParameter();
        state.ParamStates[0].Parameters.Add(new DesignStateParameter
        {
            ParameterId = "BadParam",
            DisplayName = "Bad Param",
            Type = DesignStateParameterType.Number,
            NumberValue = double.NaN,
        });

        var ex = Assert.Throws<InvalidOperationException>(() => DesignStateCanonicalProjection.ComputeHash(state));
        Assert.Contains("BadParam", ex.Message);
    }

    [Fact]
    public void ComputeHash_ShouldThrow_WhenNumberParameterValueIsInfinity()
    {
        var state = BuildFixedDesignStateWithParameter();
        state.ParamStates[0].Parameters.Add(new DesignStateParameter
        {
            ParameterId = "InfiniteParam",
            DisplayName = "Infinite Param",
            Type = DesignStateParameterType.Number,
            NumberValue = double.PositiveInfinity,
        });

        var ex = Assert.Throws<InvalidOperationException>(() => DesignStateCanonicalProjection.ComputeHash(state));
        Assert.Contains("InfiniteParam", ex.Message);
    }
}
