#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""make_docs_v7.py — Invoke export_to_markdown_v7.py's main() to regenerate
DesignGrammar-V7.md from DesignGrammar-V7.owl.

export_to_markdown_v7.py (generated by make_export_v7.py, ported from
export_to_markdown_v6.py) is a generic OWL-to-markdown exporter with its own
`if __name__ == "__main__"` entry point. This driver is the single, named
entry point for regenerating the V7 human-readable docs — mirroring the
V6 doc-generation chain's separation between the exporter module and the
script that runs it, and never hand-editing DesignGrammar-V7.md directly.
"""
import importlib.util
import pathlib

HERE = pathlib.Path(__file__).resolve().parent

spec = importlib.util.spec_from_file_location("export_to_markdown_v7", HERE / "export_to_markdown_v7.py")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

module.main()
print("make_docs_v7.py: DesignGrammar-V7.md regenerated via export_to_markdown_v7.main()")
